### ISSUE TITLE
high res "if/then"

### ISSUE THREAD

**Issue by macdermottt** [AppalachianVoices/ACAR#10]

**Comment by macdermottt** [comment]
-- On Community Page Map // for High Res Satellite layer, we would like to have an if/then kind of option (Matt will add a row in the database for this):

```
-> Option1 (if an area has high res) // include the high res on/off button + the slider
-> Option2 (if an area does not have high res) // hide the on/off button + slider and instead include the message "High resolution satellite imagery currently not available for this area"
```

**Comment by deal99** [comment]
I added the code to handle this - awaiting the database fields from Matt.

See: http://ilovemountains.org/communities-at-risk/inman-va?high_resolution_imagery=true
        http://ilovemountains.org/communities-at-risk/inman-va

**Comment by macdermottt** [comment]
Well, to keep this at the top of @WassonMF list of stuff to remember to do, I am going to keep this one open.  It does not actually work right now.
