### ISSUE TITLE
Incorporate "active mining by year" maps into ILM test zone 

### ISSUE THREAD

**Issue by WassonMF** [AppalachianVoices/ACAR#4]

**Comment by WassonMF** [comment]
Here's the link to the GME map:

https://mapsengine.google.com/02151825056266571727-18308525781831184728-4/mapview/?authuser=0

**Comment by WassonMF** [comment]
Ok - Map is complete and color coded. Should be ready to go.

**Comment by macdermottt** [comment]
Done!
