### ISSUE TITLE
remove "feet" row in chart

### ISSUE THREAD

**Issue by macdermottt** [AppalachianVoices/ACAR#6]

**Comment by macdermottt** [comment]
Remove the FEET row on the Chart so we will just have Acres/year of active mining (Matt and I figured out how to change to Acres, but I couldn't figure out how to remove the first Row without breaking it, though I tried to do it logically).

**Comment by macdermottt** [comment]
@WassonMF can you tell me a little more about this?  do you only want one line on the chart?  How about a picture?

**Comment by avjamiegee** [comment]
I think we're just doing Acres per year actively mined, so just the one X axis (years) and one Y axis (acres), with Y denoted by the formula ( 8036043.5 - $row[2] ) / 4047 ) in the row below:

```
    $dat[$row[0]] = array($row[1]*3.28, ( 8036043.5 - $row[2] ) / 4047 );
```

I tried to eliminate **row[1] element**, but every iteration I tried gave me a syntax error, such as: 
        $dat[$row[0]] = array( 8036043.5 - $row[2] ) / 4047 );

**Comment by avjamiegee** [comment]
Also, can you please set the Baseline to 0, and not -4000?

THANKS!
