### ISSUE TITLE
Take out greybox

### ISSUE THREAD

**Issue by macdermottt** [AppalachianVoices/ACAR#8]

**Comment by macdermottt** [comment]
Jeff, in my opinion, the greybox code generally just needs to die.  It conflicts with everything.  it is a piece.  If you can find it in your heart to remove it from the ILM header file, and maybe even delete it from the server all together, I truly believe that life will be better.

**Comment by deal99** [comment]
Roger that Toby ... I commented it out for ACAR and will eventually get it
replaced.
